language: ruby
dist: trusty
sudo: required
services:
  - postgresql
  - docker
env:
  - START_SIMPLECOV=1 RAILS_DB_ADAPTER=sqlite3
  - START_SIMPLECOV=1 RAILS_DB_ADAPTER=postgresql
  - TRAVIS=1 RAILS_DB_ADAPTER=sqlite3
addons:
  postgresql: '9.6'
  code_climate:
    repo_token:
      secure: "GWi7hiAMEgFb2pQ4ahkk8o/vyOxvJUx9gKznEGH2zrcngk+D8w+4skPdTV5qWDLqVIn9ADl9z6T/7UuMd4RMZMpsZlwG/YVFxDba9YFjZ+Rqng1+UX3h/7q7vyZOQqCxeaN5ohOS92SYo4E6uh3qWZAL/tvmAfbECtSpC5b+w8uKpvV6Fmthdg5X2dvZhA8+DpCwlEWJkDLiXLO3bakyemmyAt4wlxKdXwiUdVEuwX0eTwdWSxHFNFNIgVN8aqf+N2FgJ7GCxwZQB70CP2VL9BET3dFaMgrfx5yk0/gxqifmeqR2g3Dv6n8MMKiTVJZVftwHMiEcyzGf891w2PJYPkxUzt72XYhu+8ef/HKemlffW/82XGuO6NpynrGG7Rsr7EyELs7jcAqGEUs0Cto1nsHMJxDI3ONtviAgAAP2ts8EmfMp8SX8ITFVkoVVqx2LXgaP9Xkp/nJma4HpRAPaQo6t2dLNJdCnE1I+UJOgpdUhiY+x38+Ezvgu0CWDqn07oK7u6yiIfyfsKEzYq5w0wgWFqz6a/o0k0zOzN1BXBJvRAmPkPWy1V7In2p4/IHe00q/VT5b/nFE0GwJC1/5bm1z83qmTPFMoxp9QLaP3U5nFiCFetuPO/Tp06cCufpX+BcE5G1je0jvSpfRJOO4CgS+Gj1j1LNqiTRIvGhRCF1Y="
before_install:
  - sudo add-apt-repository ppa:jonathonf/backports -y
  - sudo apt-get update -q
  - sudo apt-get install sqlite3 -y
  - bash -c 'if [[ "${TRAVIS}" == "1" ]]; then sudo docker pull dwilkie/somleng-scfm-avf:spec; fi'
  - bash -c 'if [[ "${TRAVIS}" == "1" ]]; then sudo docker ps -a; fi'
  - bash -c 'if [[ "${TRAVIS}" == "1" ]]; then sudo docker run --rm dwilkie/somleng-scfm-avf:spec /bin/sh -c "bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rake"; fi'
before_script:
  - psql -c 'create database somleng_scfm_test;' -U postgres
  - sqlite3 --version
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
