language: ruby
dist: trusty
sudo: false
services:
  - postgresql
env:
  matrix:
    - RAILS_DB_ADAPTER=postgresql START_SIMPLECOV=1
addons:
  postgresql: '9.6'
  code_climate:
    repo_token:
      secure: "GWi7hiAMEgFb2pQ4ahkk8o/vyOxvJUx9gKznEGH2zrcngk+D8w+4skPdTV5qWDLqVIn9ADl9z6T/7UuMd4RMZMpsZlwG/YVFxDba9YFjZ+Rqng1+UX3h/7q7vyZOQqCxeaN5ohOS92SYo4E6uh3qWZAL/tvmAfbECtSpC5b+w8uKpvV6Fmthdg5X2dvZhA8+DpCwlEWJkDLiXLO3bakyemmyAt4wlxKdXwiUdVEuwX0eTwdWSxHFNFNIgVN8aqf+N2FgJ7GCxwZQB70CP2VL9BET3dFaMgrfx5yk0/gxqifmeqR2g3Dv6n8MMKiTVJZVftwHMiEcyzGf891w2PJYPkxUzt72XYhu+8ef/HKemlffW/82XGuO6NpynrGG7Rsr7EyELs7jcAqGEUs0Cto1nsHMJxDI3ONtviAgAAP2ts8EmfMp8SX8ITFVkoVVqx2LXgaP9Xkp/nJma4HpRAPaQo6t2dLNJdCnE1I+UJOgpdUhiY+x38+Ezvgu0CWDqn07oK7u6yiIfyfsKEzYq5w0wgWFqz6a/o0k0zOzN1BXBJvRAmPkPWy1V7In2p4/IHe00q/VT5b/nFE0GwJC1/5bm1z83qmTPFMoxp9QLaP3U5nFiCFetuPO/Tp06cCufpX+BcE5G1je0jvSpfRJOO4CgS+Gj1j1LNqiTRIvGhRCF1Y="
before_script:
  - bash -c 'if [[ "${DOCKER}" != "1" ]]; then psql -c "create database somleng_scfm_test;" -U postgres; fi'
script:
  - bash -c 'if [[ "${DOCKER}" = "1" ]]; then sudo docker run --rm -e RAILS_DB_ADAPTER=sqlite3 dwilkie/somleng-scfm:spec /bin/sh -c "bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rake"; else bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rake; fi'
after_success:
  - bash -c 'if [[ "${START_SIMPLECOV}" = "1" ]]; then bundle exec codeclimate-test-reporter; fi'
deploy:
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "BD5CIhzm97RiM1/q5EvI2r7XDxpL6+iuYoBms0vuZvleZFUjgN7c0JCqJ4OIk1S7DtpBKjRMppZ96b3yE/Qu28hj/qexdeEsoNUbbXuQPaLM2Zd/wtUlR0Q3RcKf0Ch1tVcBYPgUuuw2+MGFos6bYinqZtAIjY8MQ99Gs3Tg58U6igwt/ts97Bbh/QaK6DlEZ+u/xiDvAWUwXiUZTyKO0xvlZBBdJwiilNxn3Zvr9EWWAWSmx56/GyqhZXGoXLf0UGLMRZxn4SuRg56TCtqb+EMWWJ0Uf6JKq5DwSvuOVpgPIyiDHk8HKupOa+79GnqK6/U3J9yuzUB00OhSlibFGoEwdSJvMRHTJVwqUHKaCktTzyhAKSfAEHlGETr+MPJV81Jwhf8EfGvlsCMMsShMP+sudCIYoldzJck06rB0fy4uXFV0bjzwKuWqfQlr9GFKinAgVN0YNGBZSgaHu8pCDAZt3zWo+xdmuLc9BPUetgsr9z60xpIxbTO+DLaNqVWKx/pSCccYyMX0GejIFG4QTZFp6Omf9TUJQOaD5l50aGMD8doUzVAFvwTk+/1Wx7iBOAn4REpZdUzl/p3bCK3uXT59zBjcZdZSy4uUeCnoM6/yRMaotGtvnAHjUodxJp1gikqJd5lXx1Gkn3YekIx8Pk+39Sj9dlWJJddKH4gCRgQ="
    secret-access-key:
      secure: "gGB4Gr6ovx2jorEcwwgEk73kWiiCXFKLmN7aiFrp6x3iWuPFANqUNanx02WRuU3Fu4lX9GcJFsws1PGFxW9rx1UT25Dwt4PrqB0VfKJ05vZLjEOnHpmzGpK0uZG6DMe3Apcvb34uguRglpyVmWI4IKr2gB0qjHeAfJE3UI5iuxzddCRrYB+DQ7txO56AcU8vgrTHBstXGXAoi6zTu9qNjCDEvKMHQ4ds1MRoyqXj9sCcIYEZXqBtOfrO67YQI9qPmaH6NMgM8HlI8alCdvlmNZRfsNOH0y7JcED2OaiJ9hDT61nQ97nAgdyGCew4oxHIEjIcs/hmCeIJBYoYhhqZxJlDMjB7a8g1B65bPXG4d81Uy2CzKuOSLQgrGOc72emt92PL5UT+xYe6/sW0k2GC/hINah9LKZppMIKYCT5yN60gDbz5hvJjcGca6PtwrVOPaYyFlwY961Z8Hp77dC82aqJ3yAsdnoDnddThefWMccH14bipDnDcka0+vm1oY81uQHqPQP4S/3BnRJrc9dSLeyZPF6M8p+PrwV4i1zn4Afv7uupLcIYhKdSmFxWIibOZhZQpDsxdte9QDCkwouNKhQor8nfxy8EEIeXSceiFMabc691hEKzER+JxfA67F19pf9zYm+KStOw4JOOTmDK1fNZAIzb2DpRva5glkUhzTOo="
    region: eu-west-1
    app: somleng-scfm
    env: somleng-scfm-web
    bucket_name: travis.somleng-scfm.avf
    on:
      repo: dwilkie/somleng-scfm-avf
      branch: master
      condition: $RAILS_DB_ADAPTER = postgresql
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "BD5CIhzm97RiM1/q5EvI2r7XDxpL6+iuYoBms0vuZvleZFUjgN7c0JCqJ4OIk1S7DtpBKjRMppZ96b3yE/Qu28hj/qexdeEsoNUbbXuQPaLM2Zd/wtUlR0Q3RcKf0Ch1tVcBYPgUuuw2+MGFos6bYinqZtAIjY8MQ99Gs3Tg58U6igwt/ts97Bbh/QaK6DlEZ+u/xiDvAWUwXiUZTyKO0xvlZBBdJwiilNxn3Zvr9EWWAWSmx56/GyqhZXGoXLf0UGLMRZxn4SuRg56TCtqb+EMWWJ0Uf6JKq5DwSvuOVpgPIyiDHk8HKupOa+79GnqK6/U3J9yuzUB00OhSlibFGoEwdSJvMRHTJVwqUHKaCktTzyhAKSfAEHlGETr+MPJV81Jwhf8EfGvlsCMMsShMP+sudCIYoldzJck06rB0fy4uXFV0bjzwKuWqfQlr9GFKinAgVN0YNGBZSgaHu8pCDAZt3zWo+xdmuLc9BPUetgsr9z60xpIxbTO+DLaNqVWKx/pSCccYyMX0GejIFG4QTZFp6Omf9TUJQOaD5l50aGMD8doUzVAFvwTk+/1Wx7iBOAn4REpZdUzl/p3bCK3uXT59zBjcZdZSy4uUeCnoM6/yRMaotGtvnAHjUodxJp1gikqJd5lXx1Gkn3YekIx8Pk+39Sj9dlWJJddKH4gCRgQ="
    secret-access-key:
      secure: "gGB4Gr6ovx2jorEcwwgEk73kWiiCXFKLmN7aiFrp6x3iWuPFANqUNanx02WRuU3Fu4lX9GcJFsws1PGFxW9rx1UT25Dwt4PrqB0VfKJ05vZLjEOnHpmzGpK0uZG6DMe3Apcvb34uguRglpyVmWI4IKr2gB0qjHeAfJE3UI5iuxzddCRrYB+DQ7txO56AcU8vgrTHBstXGXAoi6zTu9qNjCDEvKMHQ4ds1MRoyqXj9sCcIYEZXqBtOfrO67YQI9qPmaH6NMgM8HlI8alCdvlmNZRfsNOH0y7JcED2OaiJ9hDT61nQ97nAgdyGCew4oxHIEjIcs/hmCeIJBYoYhhqZxJlDMjB7a8g1B65bPXG4d81Uy2CzKuOSLQgrGOc72emt92PL5UT+xYe6/sW0k2GC/hINah9LKZppMIKYCT5yN60gDbz5hvJjcGca6PtwrVOPaYyFlwY961Z8Hp77dC82aqJ3yAsdnoDnddThefWMccH14bipDnDcka0+vm1oY81uQHqPQP4S/3BnRJrc9dSLeyZPF6M8p+PrwV4i1zn4Afv7uupLcIYhKdSmFxWIibOZhZQpDsxdte9QDCkwouNKhQor8nfxy8EEIeXSceiFMabc691hEKzER+JxfA67F19pf9zYm+KStOw4JOOTmDK1fNZAIzb2DpRva5glkUhzTOo="
    region: eu-west-1
    app: somleng-scfm
    env: somleng-scfm-worker1
    bucket_name: travis.somleng-scfm.avf
    on:
      repo: dwilkie/somleng-scfm-avf
      branch: master
      condition: $RAILS_DB_ADAPTER = postgresql
